// TEMPORARY SEED DATA - Remove once real listings exist in production

import type { Listing } from "@/lib/api-client";

export const SEED_ENABLED = true;

export const SEED_DOMAINS: Listing[] = [
	// Tech/SaaS - .com domains (Low-Mid tier)
	{
		id: "seed-1",
		domainId: "seed-domain-1",
		mode: "exclusive",
		pricePeriodCents: 8900,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-1",
			fqdn: "cloudmetrics.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-2",
		domainId: "seed-domain-2",
		mode: "exclusive",
		pricePeriodCents: 45000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-2",
			fqdn: "devtools.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-3",
		domainId: "seed-domain-3",
		mode: "exclusive",
		pricePeriodCents: 65000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-3",
			fqdn: "apigateway.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-4",
		domainId: "seed-domain-4",
		mode: "shared_slugs",
		pricePeriodCents: 17500,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-4",
			fqdn: "smartanalytics.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-5",
		domainId: "seed-domain-5",
		mode: "shared_slugs",
		pricePeriodCents: 22000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-5",
			fqdn: "automationhub.com",
			verificationStatus: "verified",
		},
	},

	// Tech - .io domains (Mid tier)
	{
		id: "seed-6",
		domainId: "seed-domain-6",
		mode: "exclusive",
		pricePeriodCents: 38000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-6",
			fqdn: "deploy.io",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-7",
		domainId: "seed-domain-7",
		mode: "exclusive",
		pricePeriodCents: 29500,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-7",
			fqdn: "monitor.io",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-8",
		domainId: "seed-domain-8",
		mode: "shared_slugs",
		pricePeriodCents: 16500,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-8",
			fqdn: "buildfast.io",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-9",
		domainId: "seed-domain-9",
		mode: "shared_slugs",
		pricePeriodCents: 24000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-9",
			fqdn: "codebase.io",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-10",
		domainId: "seed-domain-10",
		mode: "exclusive",
		pricePeriodCents: 52000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-10",
			fqdn: "serverless.io",
			verificationStatus: "verified",
		},
	},

	// AI/ML - .ai domains (High tier)
	{
		id: "seed-11",
		domainId: "seed-domain-11",
		mode: "exclusive",
		pricePeriodCents: 85000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-11",
			fqdn: "neural.ai",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-12",
		domainId: "seed-domain-12",
		mode: "exclusive",
		pricePeriodCents: 72000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-12",
			fqdn: "predict.ai",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-13",
		domainId: "seed-domain-13",
		mode: "exclusive",
		pricePeriodCents: 68000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-13",
			fqdn: "automate.ai",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-14",
		domainId: "seed-domain-14",
		mode: "exclusive",
		pricePeriodCents: 79000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-14",
			fqdn: "vision.ai",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-15",
		domainId: "seed-domain-15",
		mode: "exclusive",
		pricePeriodCents: 95000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-15",
			fqdn: "chatbot.ai",
			verificationStatus: "verified",
		},
	},

	// Finance - .com domains (Mid-High tier)
	{
		id: "seed-16",
		domainId: "seed-domain-16",
		mode: "shared_slugs",
		pricePeriodCents: 34000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-16",
			fqdn: "paymentflow.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-17",
		domainId: "seed-domain-17",
		mode: "exclusive",
		pricePeriodCents: 48000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-17",
			fqdn: "cryptowallet.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-18",
		domainId: "seed-domain-18",
		mode: "shared_slugs",
		pricePeriodCents: 28000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-18",
			fqdn: "investsmart.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-19",
		domainId: "seed-domain-19",
		mode: "exclusive",
		pricePeriodCents: 42000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-19",
			fqdn: "tradingdesk.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-20",
		domainId: "seed-domain-20",
		mode: "shared_slugs",
		pricePeriodCents: 9500,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-20",
			fqdn: "budgetpro.com",
			verificationStatus: "verified",
		},
	},

	// Health/Wellness - .com domains (Low-Mid tier)
	{
		id: "seed-21",
		domainId: "seed-domain-21",
		mode: "shared_slugs",
		pricePeriodCents: 18500,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-21",
			fqdn: "healthtracker.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-22",
		domainId: "seed-domain-22",
		mode: "shared_slugs",
		pricePeriodCents: 14000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-22",
			fqdn: "wellnesscoach.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-23",
		domainId: "seed-domain-23",
		mode: "exclusive",
		pricePeriodCents: 75000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-23",
			fqdn: "telemedicine.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-24",
		domainId: "seed-domain-24",
		mode: "shared_slugs",
		pricePeriodCents: 12000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-24",
			fqdn: "nutritionplan.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-25",
		domainId: "seed-domain-25",
		mode: "exclusive",
		pricePeriodCents: 89000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-25",
			fqdn: "mentalhealth.com",
			verificationStatus: "verified",
		},
	},

	// Education - .com and .io domains (Low-Mid tier)
	{
		id: "seed-26",
		domainId: "seed-domain-26",
		mode: "shared_slugs",
		pricePeriodCents: 16000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-26",
			fqdn: "learnfast.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-27",
		domainId: "seed-domain-27",
		mode: "shared_slugs",
		pricePeriodCents: 19500,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-27",
			fqdn: "skillbuilder.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-28",
		domainId: "seed-domain-28",
		mode: "exclusive",
		pricePeriodCents: 31000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-28",
			fqdn: "academy.io",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-29",
		domainId: "seed-domain-29",
		mode: "shared_slugs",
		pricePeriodCents: 7500,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-29",
			fqdn: "tutorconnect.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-30",
		domainId: "seed-domain-30",
		mode: "shared_slugs",
		pricePeriodCents: 23000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-30",
			fqdn: "courseplatform.com",
			verificationStatus: "verified",
		},
	},

	// E-commerce - .com and .tech domains (Low-Mid tier)
	{
		id: "seed-31",
		domainId: "seed-domain-31",
		mode: "shared_slugs",
		pricePeriodCents: 21000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-31",
			fqdn: "shopify-alternative.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-32",
		domainId: "seed-domain-32",
		mode: "exclusive",
		pricePeriodCents: 27000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-32",
			fqdn: "marketplace.tech",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-33",
		domainId: "seed-domain-33",
		mode: "shared_slugs",
		pricePeriodCents: 15500,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-33",
			fqdn: "cartflow.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-34",
		domainId: "seed-domain-34",
		mode: "shared_slugs",
		pricePeriodCents: 12500,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-34",
			fqdn: "productcatalog.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-35",
		domainId: "seed-domain-35",
		mode: "exclusive",
		pricePeriodCents: 19000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-35",
			fqdn: "inventory.tech",
			verificationStatus: "verified",
		},
	},

	// Marketing - .com and .io domains (Low-Mid tier)
	{
		id: "seed-36",
		domainId: "seed-domain-36",
		mode: "shared_slugs",
		pricePeriodCents: 14500,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-36",
			fqdn: "emailcampaign.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-37",
		domainId: "seed-domain-37",
		mode: "exclusive",
		pricePeriodCents: 32000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-37",
			fqdn: "socialmedia.io",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-38",
		domainId: "seed-domain-38",
		mode: "shared_slugs",
		pricePeriodCents: 18000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-38",
			fqdn: "contentcreator.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-39",
		domainId: "seed-domain-39",
		mode: "shared_slugs",
		pricePeriodCents: 26000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-39",
			fqdn: "adtracker.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-40",
		domainId: "seed-domain-40",
		mode: "exclusive",
		pricePeriodCents: 35000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-40",
			fqdn: "influencer.io",
			verificationStatus: "verified",
		},
	},

	// Business/Productivity - .com, .co, .app domains (Low-High tier)
	{
		id: "seed-41",
		domainId: "seed-domain-41",
		mode: "exclusive",
		pricePeriodCents: 39000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-41",
			fqdn: "projectmanager.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-42",
		domainId: "seed-domain-42",
		mode: "exclusive",
		pricePeriodCents: 20500,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-42",
			fqdn: "taskflow.app",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-43",
		domainId: "seed-domain-43",
		mode: "exclusive",
		pricePeriodCents: 28500,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-43",
			fqdn: "teamwork.co",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-44",
		domainId: "seed-domain-44",
		mode: "shared_slugs",
		pricePeriodCents: 11000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-44",
			fqdn: "timetracker.app",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-45",
		domainId: "seed-domain-45",
		mode: "exclusive",
		pricePeriodCents: 44000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-45",
			fqdn: "crm-platform.com",
			verificationStatus: "verified",
		},
	},

	// Creative/Design - .com and .tech domains (Low-Mid tier)
	{
		id: "seed-46",
		domainId: "seed-domain-46",
		mode: "shared_slugs",
		pricePeriodCents: 25000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-46",
			fqdn: "designstudio.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-47",
		domainId: "seed-domain-47",
		mode: "exclusive",
		pricePeriodCents: 31000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-47",
			fqdn: "videoeditor.tech",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-48",
		domainId: "seed-domain-48",
		mode: "shared_slugs",
		pricePeriodCents: 17000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-48",
			fqdn: "photoedit.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-49",
		domainId: "seed-domain-49",
		mode: "shared_slugs",
		pricePeriodCents: 20000,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-49",
			fqdn: "brandbuilder.com",
			verificationStatus: "verified",
		},
	},
	{
		id: "seed-50",
		domainId: "seed-domain-50",
		mode: "shared_slugs",
		pricePeriodCents: 13500,
		priceClickCents: null,
		currency: "USD",
		status: "active",
		createdAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
		updatedAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
		domain: {
			id: "seed-domain-50",
			fqdn: "creativehub.co",
			verificationStatus: "verified",
		},
	},
];

export function getSeedListings(): Listing[] {
	return SEED_ENABLED ? SEED_DOMAINS : [];
}

export function isSeedListing(id: string): boolean {
	return id.startsWith("seed-");
}

